version: 2.1
jobs:
  build:
    working_directory: ~/GhostZen
    docker:
      - image: circleci/node:10.16.3
      - image: mongo:4.2.0  
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - run: cd client && npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  # test:
  #   docker:
  #     - image: circleci/node:10.16.3
  #   steps:
  #     - checkout
  #     - run: cd client && npm install
  #     - run: npm run pretest
  #     - run: npm run test
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      # - test